### ISSUE TITLE
Deprecated providedService 1.0.0

### ISSUE THREAD

**Issue by noseglid** [idleberg/atom-build-nsl#1]
Next version of Build will no longer support the `^1.0.0` of provided services. This has been deprecated since `v0.50.0` of the build package.

[Please see the documentation to upgrade to version ^2.0.0](https://github.com/noseglid/atom-build/blob/master/create-provider.md).

**Comment by noseglid** [comment]
Only this one left @idleberg!

**Comment by idleberg** [comment]
Updated this one yesterday, forgot to close the issue
